name: Recruitment System Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build project
        run: mvn clean install
      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docer image
        run: docker build -t welesonbatista/recruitment-system .
      - name: Publish docker image
        run: docker push welesonbatista/recruitment-system
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        run: docker pull welesonbatista/recruitment-system
      - name: remove container
        run: docker rm -f container recruitment-system
      - name: Run dcoker
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} --name recruitment-system welesonbatista/recruitment-system
